### ISSUE TITLE
The content is not visible

### ISSUE THREAD

**Issue by arinchat-repo** [Karthikmani345/aws-ecs-workshop#1]
I followed the instructions and cloned the repo. The readme talks about running a sh file and migrating a ECS cluster. Downloaded directory only "ecs-service-migration.sh file and Readme.md file. There is no other directory /contents that gets downloaded/cloned.

**Comment by kartikmanimuthu** [comment]
Hi  @arinchat-repo 

Thank you for bringing this to our attention. I understand your confusion regarding the missing /contents directory and other expected content.

Currently, the repository has the "ecs-service-migration" content available. The other topics mentioned in the README.md are part of our roadmap and are still under development. I apologize for any inconvenience or confusion this might have caused.

To set clearer expectations for our users, I've updated the README.md file to better reflect the current status of the repository and our plans for future content. Your feedback was invaluable in making this change.

Please continue to check back as we're actively working to expand the workshop content. If you have any other questions, concerns, or suggestions, please don't hesitate to share.

Thank you for your interest in the AWS ECS Workshop, and I appreciate your understanding!

Best regards.

**Comment by arinchat-repo** [comment]
Thanks for sharing the update

Thanks,
    Arindam
